# Generated by Django 4.2.7 on 2023-12-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpio', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('gpio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpio.gpio')),
            ],
        ),
    ]
