# Generated by Django 4.2.7 on 2023-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0005_systeminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='image_request_state',
            field=models.BooleanField(default=False),
        ),
    ]
