# Generated by Django 4.2.9 on 2024-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio', '0006_button_image_request_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=20)),
                ('updated_time', models.DateField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
